### ISSUE TITLE
Dynomite Crashes with Gossip

### ISSUE THREAD

**Issue by diegopacheco** [Netflix/dynomite#194]
I`m doing a 2 node cluster with Dynomite and Redis on AWS, all boxes on the same DC and same AZ. Looks like Dynomite is crashing when gossip is enabled(-g flag), so this is how i setup the cluster and my configs are the following:

How i have installed Dynomite
https://gist.github.com/diegopacheco/71985b88c28e07e02b49

How i Install and configured Prana
https://gist.github.com/diegopacheco/4d8391d585ee7d58dea9

Seed Node Config
[redis_rack1_node.yml]
````yaml
dyn_o_mite:
  datacenter: dc
  rack: rack1
  dyn_listen: 0.0.0.0:8101
  dyn_seeds:
  - 127.0.0.1:8101:rack1:dc:1383429731
  listen: 0.0.0.0:8102
  servers:
  - 127.0.0.1:6379:1
  tokens: '1383429731'
  secure_server_option: datacenter
  pem_key_file: conf/dynomite.pem
  data_store: 0
``` 
Im booting up the Seed node doing this:

````bash
sudo src/dynomite -c redis_rack1_node.yml -g
````

Other node Config
[redis_node.yml]
````yaml
dyn_o_mite:
  datacenter: dc
  rack: rack2
  dyn_listen: 0.0.0.0:8101
  dyn_seeds:
  - 10.0.1.67:8101:rack1:dc:1383429731
  listen: 0.0.0.0:8102
  servers:
  - 127.0.0.1:6379:1
  tokens: '1383429731'
  secure_server_option: datacenter
  pem_key_file: conf/dynomite.pem
  data_store: 0
````

Im booting up the other node doing this:

````bash
src/dynomite -c redis_node.yml -g
````

My client code using Dyno is here:
https://github.com/diegopacheco/netflixoss-pocs/tree/master/Dyno-NetflixDynomite-client-bench

I run the code doing this:
````bash
To run: ./gradlew run -PmainClass=com.github.diegopacheco.sandbox.java.jedis.bench.dyno.netflix.DynoClusterJedisSeedsDiscoveryMainBench
````

For Dyno i got this exception sometimes:

````java
Exception in thread "main" com.netflix.dyno.connectionpool.exception.FatalConnectionException: FatalConnectionException: [host=Host [name=UNKNOWN, port=0, dc: null, status: Down], latency=0(0), attempts=1]redis.clients.jedis.exceptions.JedisConnectionException: Unexpected end of stream.
        at com.netflix.dyno.jedis.JedisConnectionFactory$JedisConnection.execute(JedisConnectionFactory.java:78)
        at com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl.executeWithFailover(ConnectionPoolImpl.java:293)
        at com.netflix.dyno.jedis.DynoJedisClient.d_get(DynoJedisClient.java:232)
        at com.netflix.dyno.jedis.DynoJedisClient.get(DynoJedisClient.java:227)
        at com.github.diegopacheco.sandbox.java.jedis.bench.dyno.netflix.DynoClusterJedisMainBench.benchGet(DynoClusterJedisMainBench.java:103)
        at com.github.diegopacheco.sandbox.java.jedis.bench.dyno.netflix.DynoClusterJedisMainBench.main(DynoClusterJedisMainBench.java:38)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Unexpected end of stream.
        at redis.clients.util.RedisInputStream.ensureFill(RedisInputStream.java:198)
        at redis.clients.util.RedisInputStream.readByte(RedisInputStream.java:40)
        at redis.clients.jedis.Protocol.process(Protocol.java:131)
        at redis.clients.jedis.Protocol.read(Protocol.java:195)
        at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:282)
        at redis.clients.jedis.Connection.getBinaryBulkReply(Connection.java:201)
        at redis.clients.jedis.Connection.getBulkReply(Connection.java:190)
        at redis.clients.jedis.Jedis.get(Jedis.java:93)
        at com.netflix.dyno.jedis.DynoJedisClient$9.execute(DynoJedisClient.java:236)
        at com.netflix.dyno.jedis.DynoJedisClient$9.execute(DynoJedisClient.java:232)
        at com.netflix.dyno.jedis.JedisConnectionFactory$JedisConnection.execute(JedisConnectionFactory.java:70)
````

And other times i got this one:

````java
log4j:WARN No appenders could be found for logger (com.netflix.config.sources.URLConfigurationSource).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Exception in thread "main" com.netflix.dyno.connectionpool.exception.FatalConnectionException: FatalConnectionException: [host=Host [name=UNKNOWN, port=0, dc: null, status: Down], latency=0(0), attempts=1]redis.clients.jedis.exceptions.JedisDataException: ERR Storage: Connection timed out
        at com.netflix.dyno.jedis.JedisConnectionFactory$JedisConnection.execute(JedisConnectionFactory.java:84)
        at com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl.executeWithFailover(ConnectionPoolImpl.java:293)
        at com.netflix.dyno.jedis.DynoJedisClient.d_set(DynoJedisClient.java:957)
        at com.netflix.dyno.jedis.DynoJedisClient.set(DynoJedisClient.java:947)
        at com.github.diegopacheco.sandbox.java.jedis.bench.dyno.netflix.DynoClusterJedisMainBench.benchInsert(DynoClusterJedisMainBench.java:92)
        at com.github.diegopacheco.sandbox.java.jedis.bench.dyno.netflix.DynoClusterJedisMainBench.main(DynoClusterJedisMainBench.java:25)
Caused by: redis.clients.jedis.exceptions.JedisDataException: ERR Storage: Connection timed out
        at redis.clients.jedis.Protocol.processError(Protocol.java:116)
        at redis.clients.jedis.Protocol.process(Protocol.java:141)
        at redis.clients.jedis.Protocol.read(Protocol.java:195)
        at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:282)
        at redis.clients.jedis.Connection.getStatusCodeReply(Connection.java:181)
        at redis.clients.jedis.Jedis.set(Jedis.java:61)
        at com.netflix.dyno.jedis.DynoJedisClient$52.execute(DynoJedisClient.java:961)
        at com.netflix.dyno.jedis.DynoJedisClient$52.execute(DynoJedisClient.java:957)
        at com.netflix.dyno.jedis.JedisConnectionFactory$JedisConnection.execute(JedisConnectionFactory.java:70)
        ... 5 more
````

So after running the client the Seed node CRASHES with this:

````bash
[2015-11-19 01:15:2.158] dnode_peer_connect:1043 dnode: connected to peer '0.0.0.0' on p 25
[2015-11-19 01:15:2.159] dn_stacktrace:320 [0] /lib64/libpthread.so.0(+0xf130) [0x7fa990a0d130]
??:0
[2015-11-19 01:15:2.161] dn_stacktrace:320 [1] src/dynomite(mbuf_remove+0x2b) [0x41ffbb]
/opt/dynomite/src/dyn_mbuf.c:239 (discriminator 1)
[2015-11-19 01:15:2.164] dn_stacktrace:320 [2] src/dynomite(dnode_peer_gossip_forward+0xfb) [0x41671b]
/opt/dynomite/src/dyn_dnode_request.c:544
[2015-11-19 01:15:2.166] dn_stacktrace:320 [3] src/dynomite(dnode_peer_forward_state+0xdf) [0x41466f]
/opt/dynomite/src/dyn_dnode_peer.c:691
[2015-11-19 01:15:2.168] dn_stacktrace:320 [4] src/dynomite(core_loop+0x7e) [0x40f0fe]
/opt/dynomite/src/dyn_core.c:510
[2015-11-19 01:15:2.171] dn_stacktrace:320 [5] src/dynomite(main+0x6d8) [0x40cd28]
/opt/dynomite/src/dynomite.c:598
[2015-11-19 01:15:2.173] dn_stacktrace:320 [6] /lib64/libc.so.6(__libc_start_main+0xf5) [0x7fa99035baf5]
??:0
[2015-11-19 01:15:2.175] dn_stacktrace:320 [7] src/dynomite() [0x40d155]
??:?
[2015-11-19 01:15:2.178] signal_handler:127 signal 11 (SIGSEGV) received, core dumping
[ec2-user@ip-10-0-1-67 dynomite]$
````
Cheers,
Diego Pacheco

**Comment by timiblossom** [comment]
In the middle of something else now, will spend some time on this.

**Comment by diegopacheco** [comment]
sure, thanks in advance @timiblossom

**Comment by diegopacheco** [comment]
IF you guys have issues running the dyno client try this;

```bash
./gradlew execute -DmainClass=com.github.diegopacheco.sandbox.java.jedis.bench.dyno.netflix.DynoClusterJedisAddValueMain -Dexec.args="kdiego v1"

  ./gradlew execute -DmainClass=com.github.diegopacheco.sandbox.java.jedis.bench.dyno.netflix.DynoClusterJedisAddValueMain -Dexec.args="kdiego13 v13"
  
./gradlew execute -DmainClass=com.github.diegopacheco.sandbox.java.jedis.bench.dyno.netflix.DynoClusterJedisAddValueMain -Dexec.args="kdiego10 v10"

./gradlew execute -DmainClass=com.github.diegopacheco.sandbox.java.jedis.bench.dyno.netflix.DynoClusterJedisMainBench -Dexec.args="kdiego10 v10"

 ./gradlew execute -DmainClass=com.github.diegopacheco.sandbox.java.jedis.bench.dyno.netflix.DynoClusterJedisSeedsDiscoveryMainBench -Dexec.args="kdiego10 v10"
```

**Comment by timiblossom** [comment]
@diegopacheco can you work with the other method for the time being?  This might take a while as I need to wrap up another thing now.

**Comment by diegopacheco** [comment]
@timiblossom yes, Looks like i will be using Florida as an idea as you guys pointed out also because you said gossip is not a first class citizen and might have issues. Sure no worries, thanks :-)
