### ISSUE TITLE
Connection getting closed while reading a specific type of key

### ISSUE THREAD

**Issue by balajivenki** [Netflix/dynomite#416]
Hi,

We are using dynomite v0.5.8 and dyno v1.5.6.

When we try to read a value which is set as byte(both key and value) it fails with the following exception in dyno. 

`com.netflix.dyno.connectionpool.exception.FatalConnectionException: FatalConnectionException: [host=Host [hostname=UNKNOWN, ipAddress=UNKNOWN, port=0, rack: UNKNOWN, datacenter: UNKNOW, status: Down], latency=0(0), attempts=1]redis.clients.jedis.exceptions.JedisDataException: ERR Storage: Connection refused
	at com.netflix.dyno.jedis.JedisConnectionFactory$JedisConnection.execute(JedisConnectionFactory.java:104)
	at com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl.executeWithFailover(ConnectionPoolImpl.java:298)
	at com.netflix.dyno.jedis.DynoJedisClient.d_get(DynoJedisClient.java:2568)
	at com.netflix.dyno.jedis.DynoJedisClient.get(DynoJedisClient.java:2564)
	at ConfLoaded.main(ConfLoaded.java:37)
Caused by: redis.clients.jedis.exceptions.JedisDataException: ERR Storage: Connection refused
	at redis.clients.jedis.Protocol.processError(Protocol.java:127)
	at redis.clients.jedis.Protocol.process(Protocol.java:161)
	at redis.clients.jedis.Protocol.read(Protocol.java:215)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:340)
	at redis.clients.jedis.Connection.getBinaryBulkReply(Connection.java:259)
	at redis.clients.jedis.BinaryJedis.get(BinaryJedis.java:244)
	at com.netflix.dyno.jedis.DynoJedisClient$133.execute(DynoJedisClient.java:2571)
	at com.netflix.dyno.jedis.DynoJedisClient$133.execute(DynoJedisClient.java:2568)
	at com.netflix.dyno.jedis.JedisConnectionFactory$JedisConnection.execute(JedisConnectionFactory.java:85)
	... 4 more`

However the issue is in dynomite when we traced the log. The log files are attached from two different sample tests.

If you set a key 

> IOC-\windows\tasks\pc\update23.jobpc

with any value in my case both key and values are same. While reading lets say we read it in a loop of 5 in dynomite the connection is closed due to error 

**-ERR Storage: Connection refused**

I have made my dynomite to verbosity level 9 and collected the logs.

[dynomite-log5.txt](https://github.com/Netflix/dynomite/files/728286/dynomite-log5.txt)
[dynomite-log6.txt](https://github.com/Netflix/dynomite/files/728287/dynomite-log6.txt)

**Comment by balajivenki** [comment]
@ipapapa  and @shailesh33 any update on this? This is some weird issue and constantly happens when we use any key that has \ in it and when used keys as byte[] as the value is byte[]. Please let me know if you need more sample keys, I shall provide some.

**Comment by shailesh33** [comment]
I looked at it briefly earlier. I will work on this today.

**Comment by balajivenki** [comment]
Thanks @shailesh33  There are similar keys with \ causing the same issue. The weird thing is that if I set and get the same key in a loop of 10 then some times it fails immediately but might fail after 3 attempts or so too. To add more one another key that caused the issue was **ding.free.com**. So from the look of it, it sounds more like a security feature.

**Comment by shailesh33** [comment]
What do you mean by security feature?

**Comment by balajivenki** [comment]
@shailesh33 Since it blocks or disconnects the connection when the key has \ and domain name in it I am just speculating if it could be done purposefully as security. But I might be wrong. It was my assumption.

There are the other two keys that caused this issue too


```
IOC-hkey_current_user\software\microsoft\windows\currentversion\run\1001\3
IOC-hkey_current_user\software\microsoft\windows\currentversion\run\1004\3
```

**Comment by balajivenki** [comment]
@shailesh33  I have found few interesting scenarios.

I have 3 node local cluster say redis1, redis2 and redis3

The issue comes when I set the key and value as byte[].

The issue doesnt come when we set the key and value as string. 

When setting it as string the key lands in redis3 by the hashing.

When setting it as byte[] the node it shows is redis1 however minitor command on redis-cli says it still goes to redis3 and there are no activity on redis1. Hope this helps.

**Comment by balajivenki** [comment]
@shailesh33 The issue was caused by wrong routing reported at https://github.com/Netflix/dyno/issues/156

When the routing for binary key is fixed this should be fixed. However it might also help to have a fix at dynomite side to not to send server error too.

**Comment by balajivenki** [comment]
Closing the issue as it is not happening anymore.
