### ISSUE TITLE
ZRANGEBYSCORE fails due to decrytion failure

### ISSUE THREAD

**Issue by maryoush** [Netflix/dynomite#471]
We 
are recieving timeout while calling 

```
"ZRANGEBYSCORE" "XXXX.UNACK.YYYY.XXXX" "0.0" "1.504169738376E12" "limit" "0" "1000" "withscores"
```

Called from :
https://github.com/Netflix/dyno-queues/blob/4c2c748530545d133bbbdfe83f74bbc8ad339c8b/dyno-queues-redis/src/main/java/com/netflix/dyno/queues/redis/RedisDynoQueue.java#L538

The setup for 3 node rack of dynomite is clone of given one
```
dyn_o_mite:
  secure_server_option: rack
  read_consistency: dc_quorum
  write_consistency: dc_quorum
  datacenter: dc
  rack: rack1
  dyn_listen: XX.XX.XX.12:8101
  dyn_seeds:
    - XX.XX.XX.13:8101:rack2:dc:1383429731
    - XX.XX.XX.14:8101:rack3:dc:1383429731
  listen: 127.0.0.1:18102
  servers:
    - 127.0.0.1:6379:1 #assigned to local iface intentionally
  tokens: '1383429731'
```
What's important if we have changed the  read_consistency => dc_one the problem dissapears

Exception is thrown

```
redis.clients.jedis.exceptions.JedisDataException: ERR Peer: Connection timed out
	at com.netflix.dyno.jedis.JedisConnectionFactory$JedisConnection.execute(JedisConnectionFactory.java:138)
	at com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl.executeWithFailover(ConnectionPoolImpl.java:298)
	at com.netflix.dyno.jedis.DynoJedisClient.d_zrangeByScoreWithScores(DynoJedisClient.java:2643)
	at com.netflix.dyno.jedis.DynoJedisClient.zrangeByScoreWithScores(DynoJedisClient.java:2636)
	at com.hybris.dyno.queues.redis.RedisDynoQueue.lambda$processUnacks$12(RedisDynoQueue.java:591)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: redis.clients.jedis.exceptions.JedisDataException: ERR Peer: Connection timed out
	at redis.clients.jedis.Protocol.processError(Protocol.java:127)
	at redis.clients.jedis.Protocol.process(Protocol.java:161)
	at redis.clients.jedis.Protocol.read(Protocol.java:215)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:340)
	at redis.clients.jedis.Connection.getBinaryMultiBulkReply(Connection.java:276)
	at redis.clients.jedis.Connection.getMultiBulkReply(Connection.java:269)
	at redis.clients.jedis.Jedis.getTupledSet(Jedis.java:2162)
	at redis.clients.jedis.Jedis.zrangeByScoreWithScores(Jedis.java:2150)
	at com.netflix.dyno.jedis.DynoJedisClient$117.execute(DynoJedisClient.java:2649)
	at com.netflix.dyno.jedis.DynoJedisClient$117.execute(DynoJedisClient.java:2644)
	at com.netflix.dyno.jedis.JedisConnectionFactory$JedisConnection.execute(JedisConnectionFactory.java:114)
	... 8 common frames omitted
```

!!!The exception seem to occur only on dynomite layer!!!

The problem seems to be reproducable when reached >15k entries in the UNACKED queue.
The problem is not volatile - restart of the redis/dynomite doesn't help 

It seems that while calling zrangeByScoreWithScores during migrating back UNACKED events back to QUEUE we get into state that dynomite  could not process them.

Strangely depending on the criteria of the _ZRANGEBYSCORE_ this issue occurs or not.

It looks like the timeout is issued while XX.XX.XX.12 node getting synchronous response from one of the XX.XX.XX.13,XX.XX.XX.14 in RACK.
Actually both XX.XX.XX.13, XX.XX.XX.14 calls failed.

We have captured the logs on dynoqueue on node XX.XX.XX.12 [DQ_12.log](https://gist.github.com/maryoush/98dea5d04f0293ab9ca646d93d502468)
We have captured the logs on dynoqueue on node XX.XX.XX.13/14 [DQ_14.log](https://gist.github.com/maryoush/dc4b40e3888b24a82571ba689290e7a2)

We also captured the traffic from Redis at node XX.XX.XX.14 talking to dynomite [dump.log](https://gist.github.com/maryoush/2504e698057c0fcf9a3abfe8e0e5ec03)

**Comment by maryoush** [comment]
[](https://gist.github.com/maryoush/98dea5d04f0293ab9ca646d93d502468)

**Comment by shailesh33** [comment]
@maryoush The problem seems to be that the xx12 is sending the message with id 28825 to other peer xx13. It then receives the response but is not able to decrypt it:

[2017-08-31 09:45:43.575] dyn_aes_decrypt:367 Bad data in EVP_DecryptFinal_ex, crypto data with 16336 bytes of data

and so that message gets dropped and hence the peer timeout.Do you have logs for the xx.13 host with that message id in it?

**Comment by shailesh33** [comment]
Also is there a reason why you have encryption within the DC?

**Comment by maryoush** [comment]
Hi @shailesh33 
what additional information log you would expect to have in order to hunt down the issue ?

**Comment by shailesh33** [comment]
The logs of the other node which you missed. Also, do you need Interzone encryption?

**Comment by KowalczykBartek** [comment]
@shailesh33 honestly no, we will try to gather more logs and we will switch off encryption (because of in current setup there is no needs for encryption)

**Comment by shailesh33** [comment]
@KowalczykBartek @maryoush Any further steps on this?

**Comment by KowalczykBartek** [comment]
Hi ! I forgot to mention, seems that in newest build this doesn't appear :) We didn't test this on production I just made couple of tests on my computer - I don't know if it can be open - or if we can close this and eventually re-open ? 

Thanks !

**Comment by shailesh33** [comment]
I am interested in knowing which newest build is this? I know I fixed a decryption bug on the latest code.

**Comment by smukil** [comment]
We fixed a few decryption issues since, and haven't seen an error like the one mentioned here. Closing.
