### ISSUE TITLE
Dynomite coredumps when pem_key_file configuration is missing in yaml file for secure_server_option

### ISSUE THREAD

**Issue by rajanarayan92** [Netflix/dynomite#681]
Dynomite core dumps when pem_key_file configuration is missing in yaml file for secure_server_option. I think the software should terminate gracefully with appropriate error message instead of a crash.
Here is the yaml file configuration-
```
dyn_o_mite:
  datacenter: dc1
  rack: rack1
  dyn_listen: 127.0.0.1:8101
  dyn_seeds:
  - 127.0.0.2:8101:rack1:dc2:0
  listen: 127.0.0.1:8102
  servers:
  - 127.0.0.1:6379:1
  tokens: '0'
  secure_server_option: datacenter
  data_store: 0
  stats_listen: 0.0.0.0:22221
```
Dynomite version is (Issue is also seen in v0.7)
`This is dynomite-v0.6.14-2-g354c755`

Logs
```
[root@localhost src]# ./dynomite -c ../conf/singleNode.yml -v 11
[2019-07-09 16:59:52.257] dn_print_run:204 dynomite-v0.6.14-2-g354c755 built for Linux 3.10.0-957.21.3.el7.x86_64 x86_64 started on pid 15967
[2019-07-09 16:59:52.257] dn_print_run:210 run, rabbit run / dig that hole, forget the sun / and when at last the work is done / don't sit down / it's time to dig another one
[2019-07-09 16:59:52.257] dn_print_run:212                                                                       
     #                                      m                        
  mmm#  m   m  mmmm    mmm   mmmmm  mmm    mm#mm   mmm                
 #   #  \m m/  #   #  #   #  # # #    #      #    #   #               
 #   #   #m#   #   #  #   #  # # #    #      #    #''''               
 \#m##   \#    #   #   #m#   # # #  mm#mm    mm    #mm                
         m/
        ##

[2019-07-09 16:59:52.257] _conn_init:191 conn size 544
[2019-07-09 16:59:52.257] _dn_alloc:229 malloc(912) at 0xf09350 @ dyn_core.c:199
[2019-07-09 16:59:52.257] _dn_alloc:229 malloc(1608) at 0xf09930 @ dyn_conf.c:1449
[2019-07-09 16:59:52.257] _dn_alloc:229 malloc(48) at 0xf090f0 @ ../dyn_array.c:61
[2019-07-09 16:59:52.257] conf_open:1474 opened conf '../conf/singleNode.yml'
[2019-07-09 16:59:52.257] conf_validate_tokens:1628 conf '../conf/singleNode.yml' has valid tokens
[2019-07-09 16:59:52.257] conf_validate_structure:1694 next event 1 depth 0 seq 0
[2019-07-09 16:59:52.257] conf_validate_structure:1694 next event 3 depth 0 seq 0
[2019-07-09 16:59:52.257] conf_validate_structure:1694 next event 9 depth 0 seq 0
[2019-07-09 16:59:52.257] conf_validate_structure:1694 next event 6 depth 1 seq 0
[2019-07-09 16:59:52.257] conf_validate_structure:1694 next event 9 depth 1 seq 0
[2019-07-09 16:59:52.257] conf_validate_structure:1694 next event 6 depth 2 seq 0
[2019-07-09 16:59:52.257] conf_validate_structure:1694 next event 6 depth 2 seq 0
[2019-07-09 16:59:52.257] conf_validate_structure:1694 next event 6 depth 2 seq 0
[2019-07-09 16:59:52.257] conf_validate_structure:1694 next event 6 depth 2 seq 0
[2019-07-09 16:59:52.257] conf_validate_structure:1694 next event 6 depth 2 seq 0
[2019-07-09 16:59:52.257] conf_validate_structure:1694 next event 6 depth 2 seq 0
[2019-07-09 16:59:52.257] conf_validate_structure:1694 next event 6 depth 2 seq 0
[2019-07-09 16:59:52.257] conf_validate_structure:1694 next event 6 depth 2 seq 0
[2019-07-09 16:59:52.257] conf_validate_structure:1694 next event 6 depth 2 seq 0
[2019-07-09 16:59:52.257] conf_validate_structure:1694 next event 6 depth 2 seq 0
[2019-07-09 16:59:52.257] conf_validate_structure:1694 next event 6 depth 2 seq 0
[2019-07-09 16:59:52.257] conf_validate_structure:1694 next event 7 depth 2 seq 0
[2019-07-09 16:59:52.257] conf_validate_structure:1694 next event 6 depth 2 seq 1
[2019-07-09 16:59:52.257] conf_validate_structure:1694 next event 8 depth 2 seq 1
[2019-07-09 16:59:52.257] conf_validate_structure:1694 next event 6 depth 2 seq 0
[2019-07-09 16:59:52.257] conf_validate_structure:1694 next event 6 depth 2 seq 0
[2019-07-09 16:59:52.257] conf_validate_structure:1694 next event 6 depth 2 seq 0
[2019-07-09 16:59:52.257] conf_validate_structure:1694 next event 6 depth 2 seq 0
[2019-07-09 16:59:52.257] conf_validate_structure:1694 next event 6 depth 2 seq 0
[2019-07-09 16:59:52.257] conf_validate_structure:1694 next event 6 depth 2 seq 0
[2019-07-09 16:59:52.257] conf_validate_structure:1694 next event 6 depth 2 seq 0
[2019-07-09 16:59:52.257] conf_validate_structure:1694 next event 6 depth 2 seq 0
[2019-07-09 16:59:52.257] conf_validate_structure:1694 next event 10 depth 2 seq 0
[2019-07-09 16:59:52.257] conf_validate_structure:1694 next event 10 depth 1 seq 0
[2019-07-09 16:59:52.257] conf_validate_structure:1694 next event 4 depth 0 seq 0
[2019-07-09 16:59:52.257] conf_validate_structure:1694 next event 2 depth 0 seq 0
[2019-07-09 16:59:52.257] conf_begin_parse:1255 next begin event 1
[2019-07-09 16:59:52.257] conf_begin_parse:1255 next begin event 3
[2019-07-09 16:59:52.257] conf_begin_parse:1255 next begin event 9
[2019-07-09 16:59:52.257] conf_parse_core:1327 next event 6 depth 1 seq 0
[2019-07-09 16:59:52.257] conf_push_scalar:508 push 'dyn_o_mite'
[2019-07-09 16:59:52.257] conf_handler:1204 conf handler on 'dyn_o_mite'
[2019-07-09 16:59:52.257] _dn_alloc:229 malloc(1160) at 0xf1a9e0 @ ../dyn_array.c:61
[2019-07-09 16:59:52.257] _dn_alloc:229 malloc(24) at 0xf1ae70 @ ../dyn_array.c:61
[2019-07-09 16:59:52.257] conf_pool_init:273 init conf pool 0xf09960, 'dyn_o_mite'
[2019-07-09 16:59:52.257] conf_parse_core:1327 next event 9 depth 1 seq 0
[2019-07-09 16:59:52.257] conf_parse_core:1327 next event 6 depth 2 seq 0
[2019-07-09 16:59:52.257] conf_push_scalar:508 push 'datacenter'
[2019-07-09 16:59:52.257] conf_parse_core:1327 next event 6 depth 2 seq 0
[2019-07-09 16:59:52.257] conf_push_scalar:508 push 'dc1'
[2019-07-09 16:59:52.257] conf_handler:1213 conf handler on datacenter: dc1
[2019-07-09 16:59:52.257] conf_pop_scalar:529 pop 'dc1'
[2019-07-09 16:59:52.257] _dn_free:267 free(0xf1af10) @ dyn_string.c:55
[2019-07-09 16:59:52.257] conf_pop_scalar:529 pop 'datacenter'
[2019-07-09 16:59:52.257] _dn_free:267 free(0xf1aef0) @ dyn_string.c:55
[2019-07-09 16:59:52.257] conf_parse_core:1327 next event 6 depth 2 seq 0
[2019-07-09 16:59:52.257] conf_push_scalar:508 push 'rack'
[2019-07-09 16:59:52.257] conf_parse_core:1327 next event 6 depth 2 seq 0
[2019-07-09 16:59:52.257] conf_push_scalar:508 push 'rack1'
[2019-07-09 16:59:52.257] conf_handler:1213 conf handler on rack: rack1
[2019-07-09 16:59:52.257] conf_pop_scalar:529 pop 'rack1'
[2019-07-09 16:59:52.257] _dn_free:267 free(0xf1af30) @ dyn_string.c:55
[2019-07-09 16:59:52.257] conf_pop_scalar:529 pop 'rack'
[2019-07-09 16:59:52.257] _dn_free:267 free(0xf1aed0) @ dyn_string.c:55
[2019-07-09 16:59:52.257] conf_parse_core:1327 next event 6 depth 2 seq 0
[2019-07-09 16:59:52.257] conf_push_scalar:508 push 'dyn_listen'
[2019-07-09 16:59:52.257] conf_parse_core:1327 next event 6 depth 2 seq 0
[2019-07-09 16:59:52.257] conf_push_scalar:508 push '127.0.0.1:8101'
[2019-07-09 16:59:52.257] conf_handler:1213 conf handler on dyn_listen: 127.0.0.1:8101
[2019-07-09 16:59:52.257] conf_pop_scalar:529 pop '127.0.0.1:8101'
[2019-07-09 16:59:52.257] _dn_free:267 free(0xf1af50) @ dyn_string.c:55
[2019-07-09 16:59:52.257] conf_pop_scalar:529 pop 'dyn_listen'
[2019-07-09 16:59:52.257] _dn_free:267 free(0xf1aeb0) @ dyn_string.c:55
[2019-07-09 16:59:52.257] conf_parse_core:1327 next event 6 depth 2 seq 0
[2019-07-09 16:59:52.257] conf_push_scalar:508 push 'dyn_seeds'
[2019-07-09 16:59:52.257] conf_parse_core:1327 next event 6 depth 2 seq 0
dynomite: configuration file '../conf/singleNode.yml' syntax is invalid
[2019-07-09 16:59:52.258] conf_pop_scalar:529 pop 'dyn_seeds'
[2019-07-09 16:59:52.258] _dn_free:267 free(0xf1aff0) @ dyn_string.c:55
[2019-07-09 16:59:52.258] conf_pop_scalar:529 pop 'dyn_o_mite'
[2019-07-09 16:59:52.258] _dn_free:267 free(0xf09270) @ dyn_string.c:55
[2019-07-09 16:59:52.258] _dn_free:267 free(0xf090f0) @ ../dyn_array.c:77
[2019-07-09 16:59:52.258] _dn_free:267 free(0xf091d0) @ dyn_string.c:55
[2019-07-09 16:59:52.258] dn_stacktrace:286 [0] /lib64/libpthread.so.0(+0xf5d0) [0x7f6c3de935d0]
??:0
[2019-07-09 16:59:52.261] dn_stacktrace:286 [1] ./dynomite(string_deinit+0x1) [0x42dad1]
/home/radkathimar/dynomite/src/dyn_string.c:51
[2019-07-09 16:59:52.264] dn_stacktrace:286 [2] ./dynomite(conf_destroy+0x55) [0x411315]
/home/radkathimar/dynomite/src/dyn_conf.c:142
[2019-07-09 16:59:52.267] dn_stacktrace:286 [3] ./dynomite(conf_create+0xd8) [0x411578]
/home/radkathimar/dynomite/src/dyn_conf.c:2147
[2019-07-09 16:59:52.323] dn_stacktrace:286 [4] ./dynomite(core_start+0x86) [0x416cf6]
/home/radkathimar/dynomite/src/dyn_core.c:215
[2019-07-09 16:59:52.334] dn_stacktrace:286 [5] ./dynomite(main+0x67a) [0x40cdca]
/home/radkathimar/dynomite/src/dynomite.c:555
[2019-07-09 16:59:52.380] dn_stacktrace:286 [6] /lib64/libc.so.6(__libc_start_main+0xf5) [0x7f6c3d7d7495]
??:0
[2019-07-09 16:59:52.418] dn_stacktrace:286 [7] ./dynomite() [0x40d218]
??:?
[2019-07-09 16:59:52.467] signal_handler:123 signal 11 (SIGSEGV) received, core dumping
Segmentation fault (core dumped)
```

Back trace
```
Core was generated by `./dynomite -c ../conf/singleNode.yml -v 11'.
Program terminated with signal 11, Segmentation fault.
#0  string_deinit (str=str@entry=0x0) at dyn_string.c:51
51	  ASSERT((str->len == 0 && str->data == NULL) ||
Missing separate debuginfos, use: debuginfo-install glibc-2.17-260.el7_6.6.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.15.1-37.el7_6.x86_64 libcom_err-1.42.9-13.el7.x86_64 libgcc-4.8.5-36.el7_6.2.x86_64 libselinux-2.5-14.1.el7.x86_64 openssl-libs-1.0.2k-16.el7_6.1.x86_64 pcre-8.32-17.el7.x86_64 zlib-1.2.7-18.el7.x86_64
(gdb) bt
#0  string_deinit (str=str@entry=0x0) at dyn_string.c:51
#1  0x0000000000411315 in conf_server_deinit (cs=0x0) at dyn_conf.c:141
#2  conf_pool_deinit (cp=0xf09960) at dyn_conf.c:288
#3  conf_destroy (cf=0xf09930) at dyn_conf.c:2156
#4  0x0000000000411578 in conf_create (filename=0x7fff97d4534f "../conf/singleNode.yml") at dyn_conf.c:2146
#5  0x0000000000416cf6 in core_ctx_create (nci=0x7fff97d42db0) at dyn_core.c:214
#6  core_start (nci=nci@entry=0x7fff97d42db0) at dyn_core.c:247
#7  0x000000000040cdca in dn_run (nci=0x7fff97d42db0) at dynomite.c:555
#8  main (argc=<optimized out>, argv=0x7fff97d43198) at dynomite.c:622
[core.zip](https://github.com/Netflix/dynomite/files/3371478/core.zip)


```

**Comment by smukil** [comment]
@rajanarayan92 Thanks for raising this. This is a known issue, and we will be fixing it soon.

**Comment by rajanarayan92** [comment]
Thanks for the response @smukil
